/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Текущие настройки доступности */
        get: operations["AvailabilityRoutes_getAvailability"];
        /**
         * @description Полная замена настроек доступности.
         *     Интервалы каждого правила должны быть кратны 30 минутам и не пересекаться в рамках дня.
         */
        put: operations["AvailabilityRoutes_updateAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Владелец смотрит список предстоящих встреч (только активные, от текущего момента) */
        get: operations["BookingRoutes_list"];
        put?: never;
        /**
         * @description Гость создаёт бронирование на свободный слот.
         *     409 — слот уже занят или находится в прошлом.
         */
        post: operations["BookingRoutes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Владелец отменяет встречу (перевод в статус cancelled, слот снова свободен) */
        delete: operations["BookingRoutes_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий, на которые можно записаться */
        get: operations["EventTypeRoutes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Текущая сессия (проверка «я залогинен?») */
        get: operations["SessionRoutes_current"];
        put?: never;
        /** @description Вход владельца. Устанавливает сессионную cookie. */
        post: operations["SessionRoutes_login"];
        /** @description Выход владельца. Удаляет сессию. */
        delete: operations["SessionRoutes_logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты за период [from, to] включительно.
         *     Слоты вычисляются из правил доступности за вычетом активных бронирований;
         *     слоты в прошлом не возвращаются.
         */
        get: operations["SlotRoutes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Настройки доступности владельца: часовой пояс + набор недельных правил
         * @example {
         *       "timezone": "Europe/Moscow",
         *       "rules": [
         *         {
         *           "weekday": 1,
         *           "startTime": "10:00",
         *           "endTime": "18:00"
         *         },
         *         {
         *           "weekday": 3,
         *           "startTime": "10:00",
         *           "endTime": "14:00"
         *         }
         *       ]
         *     }
         */
        Availability: {
            /** @description Часовой пояс владельца, IANA-идентификатор (например, Europe/Moscow) */
            timezone: string;
            rules: components["schemas"]["AvailabilityRule"][];
        };
        /**
         * @description Правило доступности: повторяющийся недельный интервал,
         *     в котором владелец готов принимать звонки (например, Пн 10:00–18:00).
         */
        AvailabilityRule: {
            /**
             * Format: int32
             * @description День недели по ISO 8601: 1 — понедельник … 7 — воскресенье
             */
            weekday: number;
            /** @description Начало интервала, локальное время владельца в формате HH:MM */
            startTime: string;
            /** @description Конец интервала, локальное время владельца в формате HH:MM */
            endTime: string;
        };
        /**
         * @description Бронирование: гость занял конкретный слот под конкретный тип события
         * @example {
         *       "id": 1,
         *       "eventTypeId": 1,
         *       "startsAt": "2026-07-27T10:00:00Z",
         *       "endsAt": "2026-07-27T10:30:00Z",
         *       "guestName": "Иван Петров",
         *       "guestEmail": "ivan@example.com",
         *       "comment": "Хочу обсудить проект",
         *       "status": "active",
         *       "createdAt": "2026-07-21T12:00:00Z"
         *     }
         */
        Booking: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            eventTypeId: number;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            /** @description Комментарий гостя владельцу (тема звонка и т. п.) */
            comment?: string;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Данные для создания бронирования гостем */
        BookingCreate: {
            /** Format: int32 */
            eventTypeId: number;
            /**
             * Format: date-time
             * @description Начало выбранного слота, UTC. Должно совпадать со слотом из GET /api/slots.
             */
            startsAt: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            comment?: string;
        };
        /** @enum {string} */
        BookingStatus: "active" | "cancelled";
        /** @description 409 — конфликт: слот уже занят или находится в прошлом */
        ConflictError: {
            /** @enum {string} */
            code: "slot_unavailable";
            message: string;
        };
        /**
         * @description Тип события — то, на что гость записывается (например, «Вводный звонок»)
         * @example {
         *       "id": 1,
         *       "name": "Вводный звонок",
         *       "description": "Знакомство и обсуждение задачи",
         *       "durationMinutes": 30
         *     }
         */
        EventType: {
            /** Format: int32 */
            id: number;
            name: string;
            description?: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах. В MVP всегда 30.
             * @default 30
             */
            durationMinutes: number;
        };
        /** @description Ошибка одного поля при валидации */
        FieldError: {
            field: string;
            message: string;
        };
        /** @description 404 — ресурс не найден */
        NotFoundError: {
            /** @enum {string} */
            code: "not_found";
            message: string;
        };
        /**
         * @description Владелец календаря. В MVP владелец один, создаётся при инициализации приложения.
         * @example {
         *       "id": 1,
         *       "name": "Кирилл Чистов",
         *       "email": "owner@example.com"
         *     }
         */
        Owner: {
            /** Format: int32 */
            id: number;
            /** @description Отображаемое имя, показывается гостю на странице бронирования */
            name: string;
            /** Format: email */
            email: string;
        };
        /** @description Активная сессия */
        Session: {
            owner: components["schemas"]["Owner"];
        };
        /** @description Учётные данные владельца для входа */
        SessionCreate: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description Свободный 30-минутный слот. Вычисляется на лету из правил доступности
         *     за вычетом активных бронирований — в базе не хранится.
         * @example {
         *       "startsAt": "2026-07-27T10:00:00Z",
         *       "endsAt": "2026-07-27T10:30:00Z"
         *     }
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота, UTC
             */
            startsAt: string;
            /**
             * Format: date-time
             * @description Конец слота, UTC (startsAt + 30 минут)
             */
            endsAt: string;
        };
        /** @description 401 — нет активной сессии владельца или неверные учётные данные */
        UnauthorizedError: {
            /** @enum {string} */
            code: "unauthorized";
            message: string;
        };
        /** @description 422 — ошибка валидации входных данных */
        ValidationError: {
            /** @enum {string} */
            code: "validation_error";
            message: string;
            errors?: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AvailabilityRoutes_getAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    AvailabilityRoutes_updateAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Availability"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    BookingRoutes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    BookingRoutes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description 409 — конфликт: слот уже занят или находится в прошлом */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    BookingRoutes_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 404 — ресурс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypeRoutes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    SessionRoutes_current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    SessionRoutes_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description 401 — нет активной сессии владельца или неверные учётные данные */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    SessionRoutes_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SlotRoutes_list: {
        parameters: {
            query: {
                /** @description Начало периода, YYYY-MM-DD */
                from: string;
                /** @description Конец периода, YYYY-MM-DD */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description 422 — ошибка валидации входных данных */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
